# Generated by Django 4.1.7 on 2023-03-13 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_ropa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquillaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('tamanio', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
                ('water_proof', models.BooleanField()),
            ],
        ),
    ]
