# Generated by Django 4.1.7 on 2023-03-13 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_maquillaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=30)),
                ('material', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
                ('capacidad', models.IntegerField()),
            ],
        ),
    ]
