# Generated by Django 4.1.7 on 2023-03-29 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0008_cartera_nombre_maquillaje_nombre_ropa_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartera',
            name='nombre',
            field=models.CharField(default='jusilzgqmax5lni76ahgf99ti0ymyw', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='maquillaje',
            name='nombre',
            field=models.CharField(default='dtybtsv6x3qsmcwi9num5iga3vu6oh', max_length=30),
        ),
        migrations.AlterField(
            model_name='ropa',
            name='nombre',
            field=models.CharField(default='bsl5uuwmbqpohdelrj7amjgttvyvc1', max_length=30),
        ),
    ]
