# Generated by Django 4.1.7 on 2023-03-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0010_cartera_code_alter_cartera_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartera',
            name='code',
            field=models.CharField(default='5xihgnnk15jxhsvhdbtzgrmhzf8rle', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='maquillaje',
            name='nombre',
            field=models.CharField(default='strwplmelizxlc46kafsc8rhy3q7n0', max_length=30),
        ),
        migrations.AlterField(
            model_name='ropa',
            name='nombre',
            field=models.CharField(default='ze77grzwo8ciaktzw6zbdh0jdjyso6', max_length=30),
        ),
    ]
