# Generated by Django 4.1.7 on 2023-03-30 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppCoder', '0011_alter_cartera_code_alter_maquillaje_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartera',
            name='code',
            field=models.CharField(default='o8hxnlsvdw2orbz5ayfl5cgypw4kz1', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='maquillaje',
            name='nombre',
            field=models.CharField(default='pb1vngd6l0vaqvc3lmpjuuuyvq9nvn', max_length=30),
        ),
        migrations.AlterField(
            model_name='ropa',
            name='nombre',
            field=models.CharField(default='sf95d3m7du2bpgqmmczofd4hf0vgno', max_length=30),
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='avatares')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
