# Generated by Django 4.1.7 on 2023-03-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0012_alter_cartera_code_alter_maquillaje_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartera',
            name='code',
            field=models.CharField(default='4ppognawgypup2m2oh3kjjaw4sswal', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='maquillaje',
            name='nombre',
            field=models.CharField(default='ygqgj0pgz8cemtapzt6xsc5ylmbyly', max_length=30),
        ),
        migrations.AlterField(
            model_name='ropa',
            name='nombre',
            field=models.CharField(default='jui5v9iehnkteztzhxkwdijhl79zsj', max_length=30),
        ),
    ]
