# Generated by Django 4.1.7 on 2023-03-30 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0013_alter_cartera_code_alter_maquillaje_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('dateTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='cartera',
            name='code',
            field=models.CharField(default='p6pbbv11zxnuyvomo0dovralqeh1yt', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='maquillaje',
            name='nombre',
            field=models.CharField(default='an9pqbyln6txhp8sys2cwud14hh2wz', max_length=30),
        ),
        migrations.AlterField(
            model_name='ropa',
            name='nombre',
            field=models.CharField(default='khvxfsdz0wgoci7zhyc9cvjo0mspug', max_length=30),
        ),
    ]
