# Generated by Django 4.1.7 on 2023-03-31 00:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0014_message_alter_cartera_code_alter_maquillaje_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('subtitulo', models.CharField(max_length=30)),
                ('cuerpo', models.CharField(max_length=300)),
                ('autor', models.CharField(max_length=30)),
                ('fecha', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='blogs')),
            ],
        ),
        migrations.AlterField(
            model_name='cartera',
            name='code',
            field=models.CharField(default='gflyrks5re8ey1sn3irdmonwuhdrgy', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='maquillaje',
            name='nombre',
            field=models.CharField(default='bg0y4ywbfjil4ptugp6ocqimuxuze3', max_length=30),
        ),
        migrations.AlterField(
            model_name='ropa',
            name='nombre',
            field=models.CharField(default='pi98cpzyymfci5pzvvp2ew24otg994', max_length=30),
        ),
    ]
